### ISSUE TITLE
what is the status of this mirror?

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [mirror/chromium#19]
Not seeing any commit, is it deleted for some reason?

The official repository is no longer on github, now it's at https://chromium.googlesource.com/chromium/src.git

I have not found a Chromium github mirror that updates at least daily.

**Comment by john-peterson** [comment]
paul irish told me to delete it https://github.com/mirror/mirror/issues/3

**Comment by TimothyGu** [comment]
Unfortunately I cannot push all the refs to this repo since there are a few big files (≥100 MB) in the history. I therefore adopted the approach of forking https://github.com/ChromiumWebApps/chromium to https://github.com/mirror/chromium-1 which works around that limitation. I will soon delete this repo in favor of the other one.
